-- MLB Race to October — Task 1: Load Lahman data into BigQuery
-- Generated by mlb_data_foundation.ipynb
-- Target dataset: mlb_race_to_october (create this in your project before running)

-- =====================================================================
-- Part 1: LOAD DATA — create tables from staged Parquet
-- =====================================================================

-- People → people
LOAD DATA OVERWRITE `mlb_race_to_october.people`
FROM FILES (
  format = 'PARQUET',
  uris = ['gs://class-demo/mlb-race-to-october/lahman/People.parquet']
);

-- Batting → batting
LOAD DATA OVERWRITE `mlb_race_to_october.batting`
FROM FILES (
  format = 'PARQUET',
  uris = ['gs://class-demo/mlb-race-to-october/lahman/Batting.parquet']
);

-- Pitching → pitching
LOAD DATA OVERWRITE `mlb_race_to_october.pitching`
FROM FILES (
  format = 'PARQUET',
  uris = ['gs://class-demo/mlb-race-to-october/lahman/Pitching.parquet']
);

-- Teams → teams
LOAD DATA OVERWRITE `mlb_race_to_october.teams`
FROM FILES (
  format = 'PARQUET',
  uris = ['gs://class-demo/mlb-race-to-october/lahman/Teams.parquet']
);

-- Appearances → appearances
LOAD DATA OVERWRITE `mlb_race_to_october.appearances`
FROM FILES (
  format = 'PARQUET',
  uris = ['gs://class-demo/mlb-race-to-october/lahman/Appearances.parquet']
);

-- AllstarFull → allstar_full
LOAD DATA OVERWRITE `mlb_race_to_october.allstar_full`
FROM FILES (
  format = 'PARQUET',
  uris = ['gs://class-demo/mlb-race-to-october/lahman/AllstarFull.parquet']
);

-- AwardsPlayers → awards_players
LOAD DATA OVERWRITE `mlb_race_to_october.awards_players`
FROM FILES (
  format = 'PARQUET',
  uris = ['gs://class-demo/mlb-race-to-october/lahman/AwardsPlayers.parquet']
);

-- BattingPost → batting_post
LOAD DATA OVERWRITE `mlb_race_to_october.batting_post`
FROM FILES (
  format = 'PARQUET',
  uris = ['gs://class-demo/mlb-race-to-october/lahman/BattingPost.parquet']
);

-- PitchingPost → pitching_post
LOAD DATA OVERWRITE `mlb_race_to_october.pitching_post`
FROM FILES (
  format = 'PARQUET',
  uris = ['gs://class-demo/mlb-race-to-october/lahman/PitchingPost.parquet']
);

-- =====================================================================
-- Part 2: ALTER TABLE — add column descriptions for the agent
-- =====================================================================

-- people column descriptions
ALTER TABLE `mlb_race_to_october.people`
  ALTER COLUMN playerID SET OPTIONS(description = 'Lahman\'s universal player identifier (e.g., \'aaronha01\' for Hank Aaron, \'ruthba01\' for Babe Ruth). Preserved in original camelCase as the canonical Lahman key. The primary join column linking People to all stat tables.'),
  ALTER COLUMN birth_year SET OPTIONS(description = 'Year of birth (4-digit). NULL if unknown.'),
  ALTER COLUMN birth_month SET OPTIONS(description = 'Month of birth (1-12). NULL if unknown.'),
  ALTER COLUMN birth_day SET OPTIONS(description = 'Day of birth (1-31). NULL if unknown.'),
  ALTER COLUMN birth_city SET OPTIONS(description = 'City of birth. NULL if unknown.'),
  ALTER COLUMN birth_state SET OPTIONS(description = 'State, province, or other country subdivision of birth. NULL if unknown.'),
  ALTER COLUMN birth_country SET OPTIONS(description = 'Country of birth. NULL if unknown.'),
  ALTER COLUMN death_year SET OPTIONS(description = 'Year of death (4-digit). NULL if the player is still living or death year is unknown.'),
  ALTER COLUMN death_month SET OPTIONS(description = 'Month of death (1-12). NULL if living or unknown.'),
  ALTER COLUMN death_day SET OPTIONS(description = 'Day of death (1-31). NULL if living or unknown.'),
  ALTER COLUMN death_city SET OPTIONS(description = 'City of death. NULL if living or unknown.'),
  ALTER COLUMN death_state SET OPTIONS(description = 'State or country subdivision of death. NULL if living or unknown.'),
  ALTER COLUMN death_country SET OPTIONS(description = 'Country of death. NULL if living or unknown.'),
  ALTER COLUMN name_first SET OPTIONS(description = 'First name as commonly known.'),
  ALTER COLUMN name_last SET OPTIONS(description = 'Last name.'),
  ALTER COLUMN name_given SET OPTIONS(description = 'Full given name(s) at birth, including middle names.'),
  ALTER COLUMN weight_lbs SET OPTIONS(description = 'Listed playing weight in pounds. NULL if unknown.'),
  ALTER COLUMN height_inches SET OPTIONS(description = 'Listed playing height in inches. NULL if unknown.'),
  ALTER COLUMN bats SET OPTIONS(description = 'Batting handedness: \'L\' (left), \'R\' (right), \'B\' (both / switch hitter). NULL if unknown.'),
  ALTER COLUMN throws SET OPTIONS(description = 'Throwing handedness: \'L\' (left), \'R\' (right). NULL if unknown.'),
  ALTER COLUMN debut_date SET OPTIONS(description = 'Date of first MLB appearance. NULL for non-players included in this table (managers, executives) who never played.'),
  ALTER COLUMN final_game_date SET OPTIONS(description = 'Date of last MLB appearance. NULL for currently active players AND for very recent debuts — Lahman stamps this only after a player is officially retired (didn\'t play the following season), so 2025 debuters who are still active will have NULL here.'),
  ALTER COLUMN bbrefID SET OPTIONS(description = 'Baseball Reference player identifier (different format from playerID). Used for cross-referencing to baseball-reference.com.'),
  ALTER COLUMN retroID SET OPTIONS(description = 'Retrosheet player identifier. Used for cross-referencing to Retrosheet play-by-play data.'),
  ALTER COLUMN name_full SET OPTIONS(description = 'Concatenation of name_first and name_last for natural-language matching (e.g., \'Babe Ruth\', \'Hank Aaron\'). Synthesized at staging time, not present in source Lahman.');

-- batting column descriptions
ALTER TABLE `mlb_race_to_october.batting`
  ALTER COLUMN playerID SET OPTIONS(description = 'Lahman\'s universal player identifier. Joins to people.playerID. Preserved in original camelCase as the canonical Lahman key.'),
  ALTER COLUMN yearID SET OPTIONS(description = 'Season year (4-digit). Preserved in original camelCase as the canonical Lahman key.'),
  ALTER COLUMN stint SET OPTIONS(description = 'Within-season stint number (1, 2, ...). A player traded mid-season has multiple rows for the same yearID, one per team. To get a player\'s full season totals, SUM across stints with GROUP BY playerID, yearID.'),
  ALTER COLUMN teamID SET OPTIONS(description = 'Team for this stint. Joins to teams.teamID. Note teamID changes when a franchise relocates; use franchID via teams to track a franchise across moves.'),
  ALTER COLUMN lgID SET OPTIONS(description = 'League ID for this stint: \'AL\', \'NL\', or historical leagues. Preserved in original camelCase.'),
  ALTER COLUMN games SET OPTIONS(description = 'Games played by this batter in this stint.'),
  ALTER COLUMN at_bats SET OPTIONS(description = 'Plate appearances excluding walks, hit-by-pitch, sacrifices, and interference. Used as the denominator for batting average.'),
  ALTER COLUMN runs SET OPTIONS(description = 'Runs scored by this batter.'),
  ALTER COLUMN hits SET OPTIONS(description = 'Hits accumulated. Singles + doubles + triples + home runs.'),
  ALTER COLUMN doubles SET OPTIONS(description = 'Doubles hit. Lahman calls this 2B.'),
  ALTER COLUMN triples SET OPTIONS(description = 'Triples hit. Lahman calls this 3B.'),
  ALTER COLUMN home_runs SET OPTIONS(description = 'Home runs hit by this batter. For batters this is offensive output; do NOT confuse with pitching.home_runs_allowed.'),
  ALTER COLUMN runs_batted_in SET OPTIONS(description = 'Runs batted in. Sometimes abbreviated RBI in baseball commentary.'),
  ALTER COLUMN stolen_bases SET OPTIONS(description = 'Bases stolen successfully.'),
  ALTER COLUMN caught_stealing SET OPTIONS(description = 'Times caught stealing.'),
  ALTER COLUMN walks SET OPTIONS(description = 'Bases on balls drawn by this batter (sometimes abbreviated BB). Includes intentional walks.'),
  ALTER COLUMN strikeouts SET OPTIONS(description = 'Times this batter struck out. Negative for offense.'),
  ALTER COLUMN intentional_walks SET OPTIONS(description = 'Intentional walks drawn (subset of walks). Tracked in Lahman from 1955 onwards; NULL for earlier seasons.'),
  ALTER COLUMN hit_by_pitch SET OPTIONS(description = 'Times hit by a pitch (offensive).'),
  ALTER COLUMN sacrifice_hits SET OPTIONS(description = 'Sacrifice bunts (sometimes called \'sacrifices\'). Distinct from sacrifice_flies.'),
  ALTER COLUMN sacrifice_flies SET OPTIONS(description = 'Sacrifice flies. Tracked from 1954 onwards; NULL for earlier seasons.'),
  ALTER COLUMN grounded_into_double_play SET OPTIONS(description = 'Times grounded into a double play. Tracked from 1933 (NL) and 1939 (AL) onwards; NULL for earlier seasons.');

-- pitching column descriptions
ALTER TABLE `mlb_race_to_october.pitching`
  ALTER COLUMN playerID SET OPTIONS(description = 'Lahman\'s universal player identifier. Joins to people.playerID.'),
  ALTER COLUMN yearID SET OPTIONS(description = 'Season year (4-digit).'),
  ALTER COLUMN stint SET OPTIONS(description = 'Within-season stint number for pitchers traded mid-season. SUM across stints for full-season totals.'),
  ALTER COLUMN teamID SET OPTIONS(description = 'Team for this stint.'),
  ALTER COLUMN lgID SET OPTIONS(description = 'League ID for this stint.'),
  ALTER COLUMN wins SET OPTIONS(description = 'Pitcher\'s wins (W).'),
  ALTER COLUMN losses SET OPTIONS(description = 'Pitcher\'s losses (L).'),
  ALTER COLUMN games SET OPTIONS(description = 'Games pitched in (any role: starter, reliever, closer).'),
  ALTER COLUMN games_started SET OPTIONS(description = 'Games started as the starting pitcher. games - games_started gives relief appearances.'),
  ALTER COLUMN complete_games SET OPTIONS(description = 'Complete games (pitcher faced every opposing batter from start to finish).'),
  ALTER COLUMN shutouts SET OPTIONS(description = 'Complete-game shutouts (no runs allowed in a 9+ inning complete game).'),
  ALTER COLUMN saves SET OPTIONS(description = 'Saves recorded under MLB save rules. Tracked from 1969 onwards; earlier values are retroactive estimates.'),
  ALTER COLUMN outs_pitched SET OPTIONS(description = 'Total outs recorded while pitching. Innings pitched = outs_pitched / 3.0. To compute IP exactly: FLOOR(outs_pitched/3) + (outs_pitched MOD 3)/10.0 in standard baseball notation.'),
  ALTER COLUMN hits_allowed SET OPTIONS(description = 'Hits allowed by this pitcher. Distinct from batting.hits.'),
  ALTER COLUMN earned_runs_allowed SET OPTIONS(description = 'Earned runs allowed (excludes runs scored due to fielding errors).'),
  ALTER COLUMN home_runs_allowed SET OPTIONS(description = 'Home runs allowed. Distinct from batting.home_runs.'),
  ALTER COLUMN walks_allowed SET OPTIONS(description = 'Walks issued (bases on balls). Distinct from batting.walks.'),
  ALTER COLUMN strikeouts SET OPTIONS(description = 'Strikeouts recorded BY this pitcher (positive for pitcher). Distinct from batting.strikeouts.'),
  ALTER COLUMN opponent_batting_avg SET OPTIONS(description = 'Opposing batters\' batting average against this pitcher (BAOpp in Lahman). Lower is better.'),
  ALTER COLUMN earned_run_avg SET OPTIONS(description = 'Earned Run Average: (earned_runs_allowed * 9) / innings_pitched. Lower is better.'),
  ALTER COLUMN intentional_walks_allowed SET OPTIONS(description = 'Intentional walks issued. Tracked from 1955 onwards.'),
  ALTER COLUMN wild_pitches SET OPTIONS(description = 'Wild pitches thrown.'),
  ALTER COLUMN batters_hit_by_pitch SET OPTIONS(description = 'Batters this pitcher hit with a pitch.'),
  ALTER COLUMN balks SET OPTIONS(description = 'Balks called against this pitcher.'),
  ALTER COLUMN batters_faced SET OPTIONS(description = 'Total batters faced (BFP in Lahman). The pitching equivalent of plate appearances.'),
  ALTER COLUMN games_finished SET OPTIONS(description = 'Games finished as the last pitcher (relief appearances completing a game). Used in older save calculations.'),
  ALTER COLUMN runs_allowed SET OPTIONS(description = 'Total runs allowed (earned + unearned).'),
  ALTER COLUMN sacrifice_hits_allowed SET OPTIONS(description = 'Sacrifice bunts allowed by this pitcher.'),
  ALTER COLUMN sacrifice_flies_allowed SET OPTIONS(description = 'Sacrifice flies allowed.'),
  ALTER COLUMN double_plays_induced SET OPTIONS(description = 'Double plays induced by this pitcher (GIDP). Distinct from batting.grounded_into_double_play which tracks the batter\'s perspective.');

-- teams column descriptions
ALTER TABLE `mlb_race_to_october.teams`
  ALTER COLUMN yearID SET OPTIONS(description = 'Season year (4-digit). Preserved in original camelCase as the canonical Lahman key.'),
  ALTER COLUMN lgID SET OPTIONS(description = 'League ID: \'AL\' (American League), \'NL\' (National League), or historical leagues — \'AA\' (American Association), \'UA\' (Union Association), \'PL\' (Players League), \'FL\' (Federal League), \'NA\' (National Association). Preserved in original camelCase as the canonical Lahman key.'),
  ALTER COLUMN teamID SET OPTIONS(description = 'Team identifier for this specific franchise-season. Note: teamID can change when a franchise relocates (e.g., the Brooklyn Dodgers and Los Angeles Dodgers have different teamIDs across years). Use franchID to track a franchise across moves.'),
  ALTER COLUMN franchID SET OPTIONS(description = 'Franchise identifier, stable across team relocations. The Dodgers franchise has franchID \'LAD\' regardless of city.'),
  ALTER COLUMN divID SET OPTIONS(description = 'Division: \'E\' (East), \'W\' (West), \'C\' (Central). NULL before 1969 (pre-divisional play).'),
  ALTER COLUMN division_rank SET OPTIONS(description = 'Final standing within division (1 = first place). For pre-1969 seasons, this is rank within the league.'),
  ALTER COLUMN games SET OPTIONS(description = 'Total games played in the regular season.'),
  ALTER COLUMN home_games SET OPTIONS(description = 'Games played at home (Ghome in Lahman). Useful when computing home/road splits.'),
  ALTER COLUMN wins SET OPTIONS(description = 'Regular season wins.'),
  ALTER COLUMN losses SET OPTIONS(description = 'Regular season losses.'),
  ALTER COLUMN won_division SET OPTIONS(description = 'True if this team won its division. NULL before 1969 (pre-divisional play).'),
  ALTER COLUMN won_wild_card SET OPTIONS(description = 'True if this team won a wild card berth. NULL before 1994 (Wild Card era began in 1994). Number of wild cards per league increased from 1 (1994-2011) to 2 (2012-2021) to 3 (2022 onwards).'),
  ALTER COLUMN won_league SET OPTIONS(description = 'True if this team won the pennant (league championship; for the World Series era this means making the World Series).'),
  ALTER COLUMN won_world_series SET OPTIONS(description = 'True if this team won the World Series. The World Series began in 1903; NULL for 1904 and 1994 (no WS played) and for most pre-1903 seasons. Some 19th-century postseason events (1880s AA-NL championship series, Temple Cup) ARE coded as won_world_series=True, so a small number of pre-1903 entries will be True.'),
  ALTER COLUMN runs_scored SET OPTIONS(description = 'Total runs scored by this team\'s offense in the regular season.'),
  ALTER COLUMN at_bats SET OPTIONS(description = 'Team total at-bats.'),
  ALTER COLUMN hits SET OPTIONS(description = 'Team total hits (offensive). For hits allowed by team pitching see hits_allowed.'),
  ALTER COLUMN doubles SET OPTIONS(description = 'Team total doubles hit (offensive).'),
  ALTER COLUMN triples SET OPTIONS(description = 'Team total triples hit (offensive).'),
  ALTER COLUMN home_runs SET OPTIONS(description = 'Team total home runs hit (offensive). For HRs allowed by pitching see home_runs_allowed.'),
  ALTER COLUMN walks SET OPTIONS(description = 'Team total walks drawn by batters (offensive). For walks issued by pitchers see walks_allowed.'),
  ALTER COLUMN strikeouts SET OPTIONS(description = 'Team total strikeouts BY batters (negative for offense). For strikeouts recorded BY pitchers see strikeouts_pitched.'),
  ALTER COLUMN stolen_bases SET OPTIONS(description = 'Team total stolen bases.'),
  ALTER COLUMN caught_stealing SET OPTIONS(description = 'Team total times caught stealing.'),
  ALTER COLUMN hit_by_pitch SET OPTIONS(description = 'Team total times batters were hit by a pitch (offensive). For batters hit BY this team\'s pitchers, that data is not in Teams.'),
  ALTER COLUMN sacrifice_flies SET OPTIONS(description = 'Team total sacrifice flies (offensive).'),
  ALTER COLUMN runs_allowed SET OPTIONS(description = 'Total runs allowed by this team\'s pitching staff. Includes both earned and unearned runs.'),
  ALTER COLUMN earned_runs_allowed SET OPTIONS(description = 'Total earned runs allowed by team pitching (excludes runs scored due to fielding errors).'),
  ALTER COLUMN earned_run_avg SET OPTIONS(description = 'Team ERA: earned runs allowed per 9 innings pitched.'),
  ALTER COLUMN complete_games SET OPTIONS(description = 'Team complete games (a single pitcher faced every batter from start to finish without relief).'),
  ALTER COLUMN shutouts SET OPTIONS(description = 'Team shutouts (pitching staff allowed zero runs in a 9+ inning game).'),
  ALTER COLUMN saves SET OPTIONS(description = 'Team saves recorded by relief pitchers.'),
  ALTER COLUMN outs_pitched SET OPTIONS(description = 'Total outs recorded while pitching. Innings pitched = outs_pitched / 3.'),
  ALTER COLUMN hits_allowed SET OPTIONS(description = 'Total hits allowed by team pitching.'),
  ALTER COLUMN home_runs_allowed SET OPTIONS(description = 'Total home runs allowed by team pitching.'),
  ALTER COLUMN walks_allowed SET OPTIONS(description = 'Total walks (bases on balls) issued by team pitching.'),
  ALTER COLUMN strikeouts_pitched SET OPTIONS(description = 'Total strikeouts recorded BY team pitchers (positive for defense). Distinct from \'strikeouts\' which is batters\' strikeouts.'),
  ALTER COLUMN errors SET OPTIONS(description = 'Total fielding errors committed.'),
  ALTER COLUMN double_plays SET OPTIONS(description = 'Total double plays turned defensively.'),
  ALTER COLUMN fielding_pct SET OPTIONS(description = 'Team fielding percentage: (putouts + assists) / (putouts + assists + errors).'),
  ALTER COLUMN team_name SET OPTIONS(description = 'Full team name as known in this season (e.g., \'New York Yankees\', \'Brooklyn Dodgers\').'),
  ALTER COLUMN park_name SET OPTIONS(description = 'Home park name for this season.'),
  ALTER COLUMN home_attendance SET OPTIONS(description = 'Total home attendance for the season.'),
  ALTER COLUMN batting_park_factor SET OPTIONS(description = 'Park factor for batting effects (BPF in Lahman). 100 is league-neutral; values >100 indicate the park favors offense, <100 favors pitching. Computed by Lahman from home/road run-scoring ratios.'),
  ALTER COLUMN pitching_park_factor SET OPTIONS(description = 'Park factor for pitching effects (PPF in Lahman). 100 is league-neutral. Computed similarly to batting_park_factor.'),
  ALTER COLUMN teamIDBR SET OPTIONS(description = 'Baseball Reference team ID for this season.'),
  ALTER COLUMN teamIDlahman45 SET OPTIONS(description = 'Legacy Lahman v4.5 team ID. Used for cross-referencing older Lahman datasets.'),
  ALTER COLUMN teamIDretro SET OPTIONS(description = 'Retrosheet team ID for this season.');

-- appearances column descriptions
ALTER TABLE `mlb_race_to_october.appearances`
  ALTER COLUMN yearID SET OPTIONS(description = 'Season year (4-digit).'),
  ALTER COLUMN teamID SET OPTIONS(description = 'Team for this row.'),
  ALTER COLUMN lgID SET OPTIONS(description = 'League ID.'),
  ALTER COLUMN playerID SET OPTIONS(description = 'Lahman\'s universal player identifier.'),
  ALTER COLUMN games_total SET OPTIONS(description = 'Total games appeared in any capacity for this team this season (G_all in Lahman).'),
  ALTER COLUMN games_started SET OPTIONS(description = 'Games started in any defensive position.'),
  ALTER COLUMN games_batting SET OPTIONS(description = 'Games in which the player batted.'),
  ALTER COLUMN games_defense SET OPTIONS(description = 'Games played defensively (any position including DH).'),
  ALTER COLUMN games_pitcher SET OPTIONS(description = 'Games appeared as a pitcher.'),
  ALTER COLUMN games_catcher SET OPTIONS(description = 'Games appeared as a catcher.'),
  ALTER COLUMN games_first_base SET OPTIONS(description = 'Games appeared at first base.'),
  ALTER COLUMN games_second_base SET OPTIONS(description = 'Games appeared at second base.'),
  ALTER COLUMN games_third_base SET OPTIONS(description = 'Games appeared at third base.'),
  ALTER COLUMN games_shortstop SET OPTIONS(description = 'Games appeared at shortstop.'),
  ALTER COLUMN games_left_field SET OPTIONS(description = 'Games appeared in left field.'),
  ALTER COLUMN games_center_field SET OPTIONS(description = 'Games appeared in center field.'),
  ALTER COLUMN games_right_field SET OPTIONS(description = 'Games appeared in right field.'),
  ALTER COLUMN games_outfield SET OPTIONS(description = 'Total outfield games (G_OF). Equals games_left_field + games_center_field + games_right_field. Useful for queries that don\'t care about the specific outfield position.'),
  ALTER COLUMN games_designated_hitter SET OPTIONS(description = 'Games as DH. The DH was introduced in the AL in 1973 and adopted by the NL in 2022.'),
  ALTER COLUMN games_pinch_hitter SET OPTIONS(description = 'Games as a pinch hitter.'),
  ALTER COLUMN games_pinch_runner SET OPTIONS(description = 'Games as a pinch runner.');

-- allstar_full column descriptions
ALTER TABLE `mlb_race_to_october.allstar_full`
  ALTER COLUMN playerID SET OPTIONS(description = 'Lahman\'s universal player identifier.'),
  ALTER COLUMN yearID SET OPTIONS(description = 'Season year of the All-Star Game.'),
  ALTER COLUMN game_num SET OPTIONS(description = 'Game number within the season: 1 or 2. Most years have a single ASG (game_num=1). From 1959-1962 MLB held two All-Star Games per season; those rows have game_num=2 for the second game.'),
  ALTER COLUMN gameID SET OPTIONS(description = 'Retrosheet-style identifier for the specific All-Star Game. Preserved in camelCase.'),
  ALTER COLUMN teamID SET OPTIONS(description = 'The player\'s team during the season they were selected (not the AL/NL ASG roster).'),
  ALTER COLUMN lgID SET OPTIONS(description = 'League the player represented in the ASG (\'AL\' or \'NL\').'),
  ALTER COLUMN games_played SET OPTIONS(description = '1 if the player actually appeared in the ASG, 0 or NULL if they were selected but didn\'t play (injury, manager\'s discretion, etc.). Counts of All-Star selections should NOT filter on this column; counts of All-Star appearances should.'),
  ALTER COLUMN starting_position SET OPTIONS(description = 'Position number (1-9) if the player started the game, NULL otherwise. 1=P, 2=C, 3=1B, 4=2B, 5=3B, 6=SS, 7=LF, 8=CF, 9=RF, 10=DH (DH used in some interleague-rule years).');

-- awards_players column descriptions
ALTER TABLE `mlb_race_to_october.awards_players`
  ALTER COLUMN playerID SET OPTIONS(description = 'Lahman\'s universal player identifier.'),
  ALTER COLUMN awardID SET OPTIONS(description = 'Award name as a string. Common values: \'Most Valuable Player\', \'Cy Young Award\', \'Rookie of the Year\', \'Gold Glove\', \'Silver Slugger\', \'Manager of the Year\', \'World Series MVP\', \'ALCS MVP\', \'NLCS MVP\', \'Reliever of the Year\'. Use DISTINCT awardID to enumerate possibilities. Preserved in camelCase as the canonical Lahman key.'),
  ALTER COLUMN yearID SET OPTIONS(description = 'Season the award was given for.'),
  ALTER COLUMN lgID SET OPTIONS(description = 'League the award was given in: \'AL\', \'NL\', or \'ML\' for awards given league-agnostically (e.g., World Series MVP).'),
  ALTER COLUMN tie SET OPTIONS(description = 'True if the award was shared (ties between multiple winners), NULL otherwise. NOT False — Lahman uses NULL for the non-tie case rather than \'N\'.'),
  ALTER COLUMN notes SET OPTIONS(description = 'Free-text notes about the award (e.g., position for Gold Gloves like \'CF\', \'P\'; specific designation like \'pitcher\' or \'outfield\' for Silver Slugger). NULL for most awards.');

-- batting_post column descriptions
ALTER TABLE `mlb_race_to_october.batting_post`
  ALTER COLUMN yearID SET OPTIONS(description = 'Season year. Postseason follows the regular season of the same yearID.'),
  ALTER COLUMN round SET OPTIONS(description = 'Postseason round identifier. Common values: \'WS\' (World Series), \'NLCS\' / \'ALCS\' (League Championship Series), \'NLDS\' / \'ALDS\' (League Division Series), \'NLWC\' / \'ALWC\' (Wild Card round, 2012 onwards), \'WC\' (single Wild Card game, 2012-2019), and historical rounds like \'CS\' (19th-century championship series).'),
  ALTER COLUMN playerID SET OPTIONS(description = 'Lahman\'s universal player identifier.'),
  ALTER COLUMN teamID SET OPTIONS(description = 'Team during this postseason round.'),
  ALTER COLUMN lgID SET OPTIONS(description = 'League ID.'),
  ALTER COLUMN games SET OPTIONS(description = 'Games played in this postseason round.'),
  ALTER COLUMN at_bats SET OPTIONS(description = 'Postseason at-bats in this round.'),
  ALTER COLUMN runs SET OPTIONS(description = 'Postseason runs scored in this round.'),
  ALTER COLUMN hits SET OPTIONS(description = 'Postseason hits in this round.'),
  ALTER COLUMN doubles SET OPTIONS(description = 'Doubles hit in this round.'),
  ALTER COLUMN triples SET OPTIONS(description = 'Triples hit in this round.'),
  ALTER COLUMN home_runs SET OPTIONS(description = 'Home runs hit in this round (offensive).'),
  ALTER COLUMN runs_batted_in SET OPTIONS(description = 'RBI in this round.'),
  ALTER COLUMN stolen_bases SET OPTIONS(description = 'Stolen bases in this round.'),
  ALTER COLUMN caught_stealing SET OPTIONS(description = 'Caught stealing in this round.'),
  ALTER COLUMN walks SET OPTIONS(description = 'Walks drawn in this round.'),
  ALTER COLUMN strikeouts SET OPTIONS(description = 'Strikeouts in this round.'),
  ALTER COLUMN intentional_walks SET OPTIONS(description = 'Intentional walks drawn.'),
  ALTER COLUMN hit_by_pitch SET OPTIONS(description = 'Times hit by pitch in this round.'),
  ALTER COLUMN sacrifice_hits SET OPTIONS(description = 'Sacrifice bunts in this round.'),
  ALTER COLUMN sacrifice_flies SET OPTIONS(description = 'Sacrifice flies in this round.'),
  ALTER COLUMN grounded_into_double_play SET OPTIONS(description = 'Grounded into double plays in this round.');

-- pitching_post column descriptions
ALTER TABLE `mlb_race_to_october.pitching_post`
  ALTER COLUMN playerID SET OPTIONS(description = 'Lahman\'s universal player identifier.'),
  ALTER COLUMN yearID SET OPTIONS(description = 'Season year.'),
  ALTER COLUMN round SET OPTIONS(description = 'Postseason round identifier (see batting_post.round for full list of values).'),
  ALTER COLUMN teamID SET OPTIONS(description = 'Team during this postseason round.'),
  ALTER COLUMN lgID SET OPTIONS(description = 'League ID.'),
  ALTER COLUMN wins SET OPTIONS(description = 'Pitcher\'s wins in this round.'),
  ALTER COLUMN losses SET OPTIONS(description = 'Pitcher\'s losses in this round.'),
  ALTER COLUMN games SET OPTIONS(description = 'Games pitched in this round.'),
  ALTER COLUMN games_started SET OPTIONS(description = 'Games started in this round.'),
  ALTER COLUMN complete_games SET OPTIONS(description = 'Complete games in this round.'),
  ALTER COLUMN shutouts SET OPTIONS(description = 'Shutouts in this round.'),
  ALTER COLUMN saves SET OPTIONS(description = 'Saves in this round.'),
  ALTER COLUMN outs_pitched SET OPTIONS(description = 'Total outs recorded pitching in this round. IP = outs_pitched / 3.'),
  ALTER COLUMN hits_allowed SET OPTIONS(description = 'Hits allowed in this round.'),
  ALTER COLUMN earned_runs_allowed SET OPTIONS(description = 'Earned runs allowed in this round.'),
  ALTER COLUMN home_runs_allowed SET OPTIONS(description = 'Home runs allowed in this round.'),
  ALTER COLUMN walks_allowed SET OPTIONS(description = 'Walks issued in this round.'),
  ALTER COLUMN strikeouts SET OPTIONS(description = 'Strikeouts BY this pitcher in this round.'),
  ALTER COLUMN opponent_batting_avg SET OPTIONS(description = 'Opposing batting average against this pitcher in this round.'),
  ALTER COLUMN earned_run_avg SET OPTIONS(description = 'ERA in this round.'),
  ALTER COLUMN intentional_walks_allowed SET OPTIONS(description = 'Intentional walks issued in this round.'),
  ALTER COLUMN wild_pitches SET OPTIONS(description = 'Wild pitches in this round.'),
  ALTER COLUMN batters_hit_by_pitch SET OPTIONS(description = 'Batters hit by this pitcher in this round.'),
  ALTER COLUMN balks SET OPTIONS(description = 'Balks in this round.'),
  ALTER COLUMN batters_faced SET OPTIONS(description = 'Batters faced in this round.'),
  ALTER COLUMN games_finished SET OPTIONS(description = 'Games finished in this round (relief appearances closing out games).'),
  ALTER COLUMN runs_allowed SET OPTIONS(description = 'Total runs allowed in this round.'),
  ALTER COLUMN sacrifice_hits_allowed SET OPTIONS(description = 'Sacrifice bunts allowed in this round.'),
  ALTER COLUMN sacrifice_flies_allowed SET OPTIONS(description = 'Sacrifice flies allowed in this round.'),
  ALTER COLUMN double_plays_induced SET OPTIONS(description = 'Double plays induced in this round.');
