-- MLB Race to October — Task 2: Train and evaluate the playoff probability model
-- Generated by mlb_data_foundation.ipynb
-- Target dataset: mlb_race_to_october (must contain the teams table from Task 1)

-- =====================================================================
-- Step 1: Train the model
-- =====================================================================

CREATE OR REPLACE MODEL `mlb_race_to_october.playoff_probability`
OPTIONS (
  model_type = 'LOGISTIC_REG',
  input_label_cols = ['played_postseason'],
  auto_class_weights = TRUE
) AS
SELECT
  -- Target: did this team play in the postseason?
  COALESCE(won_division, FALSE)
    OR COALESCE(won_wild_card, FALSE)
    OR COALESCE(won_league, FALSE)
    OR COALESCE(won_world_series, FALSE)
    AS played_postseason,
  -- Features
  wins / games AS winning_pct,
  runs_scored - runs_allowed AS run_differential,
  earned_run_avg
FROM `mlb_race_to_october.teams`
WHERE yearID BETWEEN 1994 AND 2024;

-- =====================================================================
-- Step 2: Evaluate on the 2025 holdout
-- =====================================================================

SELECT *
FROM ML.EVALUATE(
  MODEL `mlb_race_to_october.playoff_probability`,
  (
    SELECT
      COALESCE(won_division, FALSE)
        OR COALESCE(won_wild_card, FALSE)
        OR COALESCE(won_league, FALSE)
        OR COALESCE(won_world_series, FALSE)
        AS played_postseason,
      wins / games AS winning_pct,
      runs_scored - runs_allowed AS run_differential,
      earned_run_avg
    FROM `mlb_race_to_october.teams`
    WHERE yearID = 2025
  )
);

-- =====================================================================
-- Step 3: Per-team 2025 predictions (for sanity-checking against memory)
-- =====================================================================

SELECT
  team_name,
  yearID,
  ROUND(predicted_played_postseason_probs[OFFSET(0)].prob, 3) AS playoff_probability,
  predicted_played_postseason AS predicted_postseason,
  COALESCE(won_division, FALSE)
    OR COALESCE(won_wild_card, FALSE)
    OR COALESCE(won_league, FALSE)
    OR COALESCE(won_world_series, FALSE)
    AS actual_postseason
FROM ML.PREDICT(
  MODEL `mlb_race_to_october.playoff_probability`,
  (
    SELECT
      team_name,
      yearID,
      won_division, won_wild_card, won_league, won_world_series,
      wins / games AS winning_pct,
      runs_scored - runs_allowed AS run_differential,
      earned_run_avg
    FROM `mlb_race_to_october.teams`
    WHERE yearID = 2025
  )
)
ORDER BY playoff_probability DESC;
